### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by frozzare**
**Type of change**

- [X] New feature
- [ ] Bug fix
- [ ] Security patch
- [ ] Documentation update

**Description**

Adding CodeQL analysis!

**Related issue**

**Motivation**

**Checklist**

- [X] I have read the **CONTRIBUTING** document.
- [X] I have read and accepted the **Code of conduct**
- [X] Tests passes.
- [X] Style lints passes.
- [ ] Documentation of new public methods exists.

### CODE REVIEW

**Comment by frozzare** [comment]
Failing test fixed in #2

**Comment by Johannestegner** [comment]
@dependabot rebase

**Comment by Johannestegner** [comment]
> 
> 
> @dependabot rebase

I guess this doesnt work, so:

 @frozzare rebase!

;D

**Comment by Johannestegner** [comment]
👍

**Pull request merged**
